var group__mpp__domains__mod =
[
    [ "mpp_define_layout Interface", "group__mpp__domains__mod.html#mpp_define_layout", null ],
    [ "mpp_define_domains Interface", "group__mpp__domains__mod.html#mpp_define_domains", null ],
    [ "mpp_define_null_domain Interface", "group__mpp__domains__mod.html#mpp_define_null_domain", null ],
    [ "mpp_copy_domain Interface", "group__mpp__domains__mod.html#mpp_copy_domain", null ],
    [ "mpp_deallocate_domain Interface", "group__mpp__domains__mod.html#mpp_deallocate_domain", null ],
    [ "mpp_modify_domain Interface", "group__mpp__domains__mod.html#mpp_modify_domain", null ],
    [ "mpp_update_domains Interface", "group__mpp__domains__mod.html#mpp_update_domains", null ],
    [ "mpp_start_update_domains Interface", "group__mpp__domains__mod.html#mpp_start_update_domains", null ],
    [ "mpp_complete_mpp_domains Interface", "group__mpp__domains__mod.html#mpp_complete_update_domains", null ],
    [ "mpp_update_nest_fine Interface", "group__mpp__domains__mod.html#mpp_update_nest_fine", null ],
    [ "mpp_update_nest_coarse Interface", "group__mpp__domains__mod.html#mpp_update_nest_coarse", null ],
    [ "mpp_get_F2C_index Interface", "group__mpp__domains__mod.html#mpp_get_F2C_index", null ],
    [ "mpp_broadcast_domain Interface", "group__mpp__domains__mod.html#mpp_broadcast_domain", null ],
    [ "mpp_update_domains_ad Interface", "group__mpp__domains__mod.html#mpp_update_domains_ad", null ],
    [ "mpp_pass_SG_to_UG", "group__mpp__domains__mod.html#mpp_pass_SG_to_UG", null ],
    [ "mpp_get_boundary Interface", "group__mpp__domains__mod.html#mpp_get_boundary", null ],
    [ "mpp_redistribute Interface", "group__mpp__domains__mod.html#mpp_redistribute", null ],
    [ "mpp_check_field Interface", "group__mpp__domains__mod.html#mpp_check_field", null ],
    [ "mpp_global_field Interface", "group__mpp__domains__mod.html#mpp_global_field", null ],
    [ "mpp_global_max Interface", "group__mpp__domains__mod.html#mpp_global_max", null ],
    [ "mpp_global_sum Interface", "group__mpp__domains__mod.html#mpp_global_sum", null ],
    [ "mpp_get_neighbor_pe Interface", "group__mpp__domains__mod.html#mpp_get_neighbor_pe", null ],
    [ "Operator Overrides for domain types", "group__mpp__domains__mod.html#operators_domains", null ],
    [ "mpp_get_compute_domain Interface", "group__mpp__domains__mod.html#mpp_get_compute_domain", null ],
    [ "mpp_get_compute_domains Interface", "group__mpp__domains__mod.html#mpp_get_compute_domains", null ],
    [ "mpp_get_data_domain Interface", "group__mpp__domains__mod.html#mpp_get_data_domain", null ],
    [ "mpp_get_global_domain Interface", "group__mpp__domains__mod.html#mpp_get_global_domain", null ],
    [ "mpp_get_memory_domain Interface", "group__mpp__domains__mod.html#mpp_get_memory_domain", null ],
    [ "mpp_set_compute_domain Interface", "group__mpp__domains__mod.html#mpp_set_compute_domain", null ],
    [ "mpp_set_data_domain Interface", "group__mpp__domains__mod.html#mpp_set_data_domain", null ],
    [ "mpp_set_global_domain Interface", "group__mpp__domains__mod.html#mpp_set_global_domain", null ],
    [ "mpp_get_pelist Interface", "group__mpp__domains__mod.html#mpp_get_pelist", null ],
    [ "mpp_get_layout Interface", "group__mpp__domains__mod.html#mpp_get_layout", null ],
    [ "mpp_nullify_domain_list Interface", "group__mpp__domains__mod.html#mpp_nullify_domain_list", null ]
];