name: Build libFMS test with autotools

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distcheck-conf-flags: [--with-mpi=no, --disable-openmp, --enable-mixed-mode, --disable-setting-flags ]
        yaml-flag: [ --with-yaml, "" ]
    container:
      image: noaagfdl/ubuntu_libfms_gnu
      env:
        FCFLAGS: "-I/usr/include"
        VERBOSE: 1
        DISTCHECK_CONFIGURE_FLAGS: "${{ matrix.distcheck-conf-flags }} ${{ matrix.yaml-flag }}"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Prepare GNU autoconf for build
      run: autoreconf -if
    - name: Configure the build
      if: ${{ matrix.distcheck-conf-flags != '--disable-setting-flags' }}
      run: ./configure ${DISTCHECK_CONFIGURE_FLAGS}
    - name: Configure the build with compiler flags
      if: ${{ matrix.distcheck-conf-flags == '--disable-setting-flags' }}
      run: ./configure ${DISTCHECK_CONFIGURE_FLAGS}
      env:
        FCFLAGS: "-fdefault-real-8 -fdefault-double-8 -fcray-pointer -ffree-line-length-none -I/usr/include"
    - name: Build the library
      run: make -j distcheck
