name: Test coupler build
on: [push, pull_request]

jobs:
  coupler-build:
    runs-on: ubuntu-latest
    container:
      image: noaagfdl/ubuntu_libfms_gnu
      env:
        FCFLAGS: "-I/usr/include" 
        VERBOSE: 1
    steps:
    - name: Checkout FMScoupler
      uses: actions/checkout@v2
      with:
        repository: 'rem1776/FMScoupler'
        ref: '6c714cd9ba4606c28a0df71cd68d5dcc73562e0f'
    - name: Checkout FMS
      uses: actions/checkout@v2
    - name: Test Null build
      run: t/null_model_build.sh --link-fms
