name: Test coupler build
on: [push, pull_request]

jobs:
  coupler-build:
    runs-on: ubuntu-latest
    container:
      image: noaagfdl/ubuntu_libfms_gnu
      env:
        FCFLAGS: "-I/usr/include" 
        VERBOSE: 1
    steps:
    - name: Checkout FMS
      uses: actions/checkout@v2
      with:
        path: FMS
    - name: Checkout FMScoupler
      uses: actions/checkout@v2
      with:
        repository: 'rem1776/FMScoupler'
        ref: 'bb323eea5285c708debeacac47f68f522bd249fb'
        path: FMScoupler
    - name: Test Null build
      run: FMScoupler/t/null_model_build.sh --link-fms
