on: [push,workflow_dispatch]
jobs:
  builds:
    runs-on: ubuntu-latest
    container: 
      image: intel/oneapi-hpckit:devel-ubuntu20.04
      #env:
        #LDFLAGS: "-L/spack/opt/spack/linux-ubuntu20.04-x86_64/intel-2021.5.0/libyaml-0.2.5/lib -lyaml"
    steps:
    - name: Prepare for build
      run: |
        apt update && apt install -y autoconf libtool automake libhdf5-dev
        wget https://github.com/Unidata/netcdf-c/archive/refs/tags/v4.8.1.tar.gz
        tar xf v4.8.1.tar.gz && ls && cd netcdf-c*
        autoreconf -if ./configure.ac && ./configure && make -j install
    - name: checkout
      uses: actions/checkout@v2
    - name: Configure
      run: autoreconf -if ./configure.ac && ./configure --enable-code-coverage --with-yaml
    - name: Compile
      run: make
    - name: Run coverage report
      run: make check-code-coverage
      id: report
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: /coverage-percent.txt
    # get coverage results from last successful main run for comparison
    - name: Download last results
      uses: dawidd6/action-download-artifact@v2
      continue-on-error: true
      with:
        workflow: coverage.yml
        branch: coverage-action
        workflow_conclusion: completed
    - name: Compare coverage
      run: |
        if [ -f code-coverage-report/coverage-percent.txt ]; then
          archive_val="`cat code-coverage-report/coverage-percent.txt`"
          if [ "`expr $archive_val '>' $RESULT`" -eq 1 ]; then
            echo "::warning title=Coverage Dropped:: Function coverage has decreased between runs from $archive_val to $RESULT"
          fi
        else
          echo "::warning title=Coverage Not Checked:: Archived results could not be downloaded"
        fi
      env:
        RESULT: ${{ steps.report.outputs.percentage }}
