name: Generate code coverage report 

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ecpe4s/hpc-me.ubuntu20.04:2022-02-07
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Prepare GNU autoconf for build
      run: autoreconf -if
    - name: Configure the build
      run: ./configure --enable-code-coverage FC=mpiifort CC=mpiicc FCFLAGS="`nf-config --fflags`" CFLAGS="`nc-config --cflags`"
    - name: Build coverage target 
      run: make check-code-coverage 
    - name: Save the report
      uses: actions/upload-artifact@v2 
      with:
        name: coverage-report
        path: coverage-report/ 
