on: [push,workflow_dispatch]
jobs:
  builds:
    runs-on: ubuntu-latest
    container: 
      image: ryanmulhall/coverage
      env:
        LDFLAGS: "-L/spack/opt/spack/linux-ubuntu20.04-x86_64/intel-2021.5.0/libyaml-0.2.5/lib -lyaml"
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Prepare for build
      run: autoreconf -if ./configure.ac && mkdir build && cd build
    - name: Configure
      run: ./configure --enable-code-coverage --with-yaml
    - name: Compile
      run: make
    - name: Run coverage report
      run: make check-code-coverage
      id: report
    - name: Archive code coverage results
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: /coverage-percent.txt
    # get coverage results from last successful main run for comparison
    - name: Download last results
      if: success()
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: coverage.yml
        branch: coverage-action
        workflow_conclusion: completed
    - name: Compare coverage
      if: success()
      run: |
        archive_val="`cat code-coverage-report/coverage-percent.txt`"
        if [ "`expr $archive_val '>' $RESULT`" -eq 1 ]; then
          echo "::warning title=Coverage Dropped:: Coverage has been decreased between runs from $archive_val to $RESULT"
        fi
      env:
        RESULT: ${{ steps.report.outputs.percentage }}
