name: Autotools build and unit testing with NVHPC

on: push
# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nvhpc-autotools:
    runs-on: ubuntu-latest
    env:
      REGISTRY_USER: "rem1776" # TODO get username from action vars
      REGISTRY_TOKEN: "${{ secrets.IMAGE_PUSH_TOKEN }}"
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - name: checkout
      uses: actions/checkout@v4.2.2
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@v1.3.1        
    - name: Setup Spack
      uses: spack/setup-spack@v3.0.0
      with:
        buildcache: true
    - name: Set up custom build cache and build compiler
      run: |
        spack mirror add \
            --autopush \
            --oci-username-variable REGISTRY_USER \
            --oci-password-variable REGISTRY_TOKEN \
            rem-gh-cache oci://ghcr.io/rem1776/ci-cache-ubuntu
        spack compiler find
        spack install nvhpc
    - name: Install dependencies
      run: |
        spack compiler find
        spack install netcdf-fortran %nvhpc mpich %nvhpc libyaml %nvhpc
    - name: Configure
      run: |
        . /home/runner/work/FMS/FMS/spack/share/spack/setup-env.sh
        spack load nvhpc netcdf-fortran libyaml mpich
        autoreconf -if ./configure.ac
        ./configure --with-yaml
    - name: Compile
      run: |
        . /home/runner/work/FMS/FMS/spack/share/spack/setup-env.sh
        spack load nvhpc netcdf-fortran libyaml mpich
        make -j || make
    - name: Run test suite
      run: |
        spack load nvhpc netcdf-fortran libyaml mpich
        make check TEST_VERBOSE=1
