on: pull_request

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  intel-autotools:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        io-flag: ["--disable-deprecated-io", "--enable-deprecated-io"]
    container:
      image: intel/hpckit:2024.2.1-0-devel-ubuntu22.04
      env:
        CC: mpiicx
        FC: mpiifx
        CFLAGS:  "-I/libs/include"
        FCFLAGS: "-I/libs/include"
        LDFLAGS: "-L/libs/lib"
        TEST_VERBOSE: 1
        DEBUG_CFLAGS: "-O0 -g -ftrapuv -sox -traceback"
        DEBUG_FCFLAGS: "-O0 -g -traceback -check -check noarg_temp_created -check nopointer -warn -warn noerrors -fpe0 -ftrapuv"
        I_MPI_FABRICS: "shm" # needed for mpi in image
    steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: /libs
        key: ${{ runner.os }}-intel-libs
    - name: Install packages for building
      run: apt-get update && apt-get install -y autoconf libtool automake zlib1g-dev curl
    - if: steps.cache.outputs.cache-hit != 'true'
      name: Build dependencies
      run: |
        mkdir /libs
        export LD_LIBRARY_PATH="/libs/lib:$LD_LIBRARY_PATH"
        # hdf5
        wget https://support.hdfgroup.org/releases/hdf5/v1_14/v1_14_5/downloads/hdf5-1.14.5.tar.gz
        tar xf hdf5-1.14.5.tar.gz && cd hdf5-1.14.5
        ./configure --prefix=/libs
        make -j install && cd ..
        # netcdf-c
        wget https://github.com/Unidata/netcdf-c/archive/refs/tags/v4.9.2.tar.gz
        tar xf v4.9.2.tar.gz && cd netcdf-c-4.9.2
        ./configure --prefix=/libs --disable-libxml2
        make -j install
        # netcdf-fortran
        wget https://github.com/Unidata/netcdf-fortran/archive/refs/tags/v4.6.1.tar.gz
        tar xf v4.6.1.tar.gz && cd netcdf-fortran-4.6.1
        ./configure --prefix=/libs
        make -j install
        # libyaml
        wget https://github.com/yaml/libyaml/releases/download/0.2.5/yaml-0.2.5.tar.gz
        tar xf yaml-0.2.5.tar.gz && cd yaml-0.2.5
        ./configure --prefix=/libs
        make -j install && cd
    - name: checkout
      uses: actions/checkout@v4
    - name: Configure
      run: |
        autoreconf -if ./configure.ac
        export LD_LIBRARY_PATH="/libs/lib:$LD_LIBRARY_PATH"
        ./configure --with-yaml ${{ matrix.io-flag }}
    - name: Compile
      run: make -j || make
    - name: Run test suite
      run: make check LD_LIBRARY_PATH="/libs/lib:$LD_LIBRARY_PATH" TEST_VERBOSE=1
