name: Autotools build and unit testing with NVHPC

on: push
# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  intel-autotools:
    runs-on: ubuntu-latest
    container:
      image: spack/rockylinux9:1.1.1
      env:
        CC: mpicc
        FC: mpifort
        FCFLAGS: "-g -traceback"
        TEST_VERBOSE: 1
    steps:
    - name: checkout
      uses: actions/checkout@v4.2.2
    - name: Set up spack and build cache
      run: |
        spack mirror add rem-gh-cache oci://ghcr.io/rem1776/ci-cache-rocky9
        spack compiler find
    - name: Install compilers
      run: spack install nvhpc@26.1
    - name: Install dependencies
      run: spack install netcdf-fortran %%nvhpc mpich %%nvhpc libyaml %%nvhpc
    - name: Configure
      run: |
        spack load nvhpc netcdf-fortran libyaml mpich
        autoreconf -if ./configure.ac
        ./configure --with-yaml
    - name: Compile
      run: make -j || make
    - name: Run test suite
      run: make check TEST_VERBOSE=1
