on: push
jobs:
  intel-autotools:
    runs-on: self-hosted
    strategy:
      matrix:
      #  io-flag: ["--disable-deprecated-io", "--enable-deprecated-io"]
        compilers: [ "intel", "intel-classic", "intel-oneapi"]
      #  target: [ "PROD", "DEBUG" ] 
    env:
      NC_VERSION: 4.7.0
      INTEL_VERSION: 2022.1.2
      TEST_VERBOSE: 1
      I_MPI_FABRICS: "shm:ofi"
      I_MPI_OFI_PROVIDER: "tcp"
      CCOMP: ${{ matrix.compilers == 'intel-classic' && 'icc' || 'icx'}}
      FCOMP: ${{ matrix.compilers != 'intel-oneapi' && 'ifort' || 'ifx'}}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up enviroment
      run: | # writes env variables onto file to allow them to persist across steps
        module load intel/${INTEL_VERSION} impi/${INTEL_VERSION} netcdf/${NC_VERSION} hdf5
        echo "FC=`which mpi$FCOMP`"             >> "$GITHUB_ENV"
        echo "CC=`which mpi$CCOMP`"             >> "$GITHUB_ENV"
        echo "FCFLAGS=`nf-config --fflags`"     >> "$GITHUB_ENV"
        echo "CFLAGS=`nc-config --cflags`"      >> "$GITHUB_ENV"
        echo "LDFLAGS=`nc-config --libs`"       >> "$GITHUB_ENV"
    - name: Spin up nodes
      run: salloc -n 25 -p n384 -t 60 -J $GITHUB_SHA sleep 40m &
    - name: Configure
      run: |
        module load intel/${INTEL_VERSION} impi/${INTEL_VERSION} netcdf/${NC_VERSION} hdf5
        autoreconf -if ./configure.ac && mkdir build && cd build && ../configure MPI_LAUNCHER="srun -J ${GITHUB_SHA} -p n384 --mpi=pmi2"
    - name: Compile
      run: |
        module load intel/${INTEL_VERSION} impi/${INTEL_VERSION} netcdf/${NC_VERSION} hdf5
        cd build && make -j || make
    - name: Run test suite
      run: |
        module load intel/${INTEL_VERSION} impi/${INTEL_VERSION} netcdf/${NC_VERSION} hdf5
        cd build
        make check -k | tee test.out
        grep "^FAIL:" test.out
        test $? -eq 1 && exit 1
