on: push
jobs:
  intel-autotools:
    runs-on: self-hosted
    #strategy:
      #matrix:
      #  io-flag: ["--disable-deprecated-io", "--enable-deprecated-io"]
      #  compilers: [ "intel", "intel-classic", "intel-oneapi"]
      #  target: [ "PROD", "DEBUG" ] 
    env:
      CC: mpiicc
      FC: mpiifort
      NC_VERSION: 4.7.0
      INTEL_VERSION: 2022.2.2
      TEST_VERBOSE: 1
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Configure
      run: | # module loads for versions set above, hdf5 just uses latest
        module load intel/${INTEL_VERSION} impi/${INTEL_VERSION} netcdf/${NC_VERSION} hdf5
        autoreconf -if ./configure.ac 
        ./configure FCFLAGS="`nf-config --fflags`" CFLAGS="`nc-config --cflags`" LDFLAGS="`nc-config --libs`"
      #env:
      #  CC: mpifc -fc=${{ matrix.compilers == 'intel-classic' && 'icc' || 'icx'}}
      #  FC: mpifc -fc=${{ matrix.compilers != 'intel-oneapi' && 'ifort' || 'ifx'}}
    - name: Compile
      run: make -j || make
    - name: Run test suite
      run: make check TEST_VERBOSE=1
