on: push
jobs:
  intel-autotools:
    runs-on: self-hosted
    #strategy:
      #matrix:
      #  io-flag: ["--disable-deprecated-io", "--enable-deprecated-io"]
    env:
      CC: mpiicc
      FC: mpiifort
      TEST_VERBOSE: 1
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Configure
      run: |
        module load intel/2022.1.2 impi/2022.1.2 hdf5/1.10.6 netcdf/4.7.0
        autoreconf -if ./configure.ac
        ./configure FCFLAGS="`nf-config --fflags`" CFLAGS="`nc-config --cflags`"
    - name: Compile
      run: make -j || make
    - name: Run test suite
      run: make check TEST_VERBOSE=1
