on: push
jobs:
  makecheck:
    runs-on: [self-hosted, cloud]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Spin up nodes
      run: salloc -n 25 -p n384 -t 60 -J $GITHUB_SHA sleep 40m &
    - name: Run build script
      run: /contrib/fms_intel_ci/fms_container_run_full.sh
