name: Generate and host documentation 

## run on push for now
on: [push]

jobs:
  update_docs:
    runs-on: ubuntu-latest
    container:
      image: underwoo/ubuntu_libfms_gnu
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup repo 
        run: |
          autoreconf -if
          ./configure --enable-docs
      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: 'docs/Doxyfile'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
