on: release 
jobs:
  add-dev-to-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    - name: Append version with dev
      run: sed -i '/20[0-9][0-9]\.[0-9][0-9]/ s/]/-dev]/' configure.ac 
    - name: Create pull request
      uses: peter-evans/create-pull-request@v4 
